ClientID: 2 
ClientSecret: aCC10gFfbP0zXE7EFLQZnZIWVUr4nFwRjU7QkiO2
GlobalPreferenceInCaseOfMergeConflict: devnagri 
ProjectKey:  25b8d9d922b61aa445c0802e09a68eee 
RootFolder: langs 
SourceLanguage: en 
TargetLanguages: 
- hi 
- pa
- ta
- ma
AccessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjM0YmViYTk5NzVkN2E2OWEyOTJmMjJlZDY0ZDZmODI2ZDk4ZmE2MzZiN2ViNzczMmU5NDYxNGE5NDJkZDdiYzEwMTM1MTg1OWZlNjQ4NTA0In0.eyJhdWQiOiIzIiwianRpIjoiMzRiZWJhOTk3NWQ3YTY5YTI5MmYyMmVkNjRkNmY4MjZkOThmYTYzNmI3ZWI3NzMyZTk0NjE0YTk0MmRkN2JjMTAxMzUxODU5ZmU2NDg1MDQiLCJpYXQiOjE1MTgzNDIxNTgsIm5iZiI6MTUxODM0MjE1OCwiZXhwIjoxNTQ5ODc4MTU4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.J2flrWJ4FHnyDAoQFQzeQ0ZAkSI871yNNKVMnX39DRE12ZKI5tchofU_DEoZqWtbQQPIytb8lVSBmfwFmqqeoU-e53yZWCl_QvFwTu6T7o3dvfDCPlcd2_YCUcJBBozbooBopfqZEiQueaYRbWy057wfb5c1qd-q6oQsiSjGy282B2jcrJXKFd0-S5xn3EqOrdJql7meKy1N2hC78WUFMMlNF4zXa1X5o8S7_Gmu9Pop8AS__ewVH8ik2iqYWeNeVJqVU5zMhhNNmvSWdGIthunEVyJRxnqUS3C2vCVbhGSiGfj6xT-y3-Jfz6MUQR7SfFHzj8Prc0PSQ63O2p6ucjCyAls1-_0MCmxotFhloL3qWJ67i07792tFaXD33m6zq1NwUfFZGenSHGiy_6E42r69dzIe-Pk_NS59QJZ3mUTVwpAHjJfOFfpNoJWuwG9DM0yzCbUyuW-b2p8E7Wmh-_NE2BFI3u8uvUPVoWvs_1p54U5lF2v24lxIo09QCMoo7yIhDiQo5vjxcxIOYbbo4p4W9RRm0VHYrUDYp9on_-_oW0b6w97e4AMvXuKShXVOORA7I2wTX4GNdUG2Km03XdVglnkjkGj5LDl0tYTbOXTi5sQzKI8hP3OSEjAPGHM7tJEIu7EIGGjKONM0Vw3zuBWE3NOZ6bl7Jb9ffnzvkxU