ClientID: "Client ID"

ClientSecret: "Client Secret"

ProjectKey: "Project Key"

AccessToken: "Access Token"

Localizationfolder: "Localization Folder"

LanguagesToBeTranslated:
  - en
  - hi

RootDir: "./"

// TODO: Choose one  =>  devnagri / local
GlobalPreferenceInCaseOfMergeConflict: "Remote"
