ClientID: "Client ID"

ClientSecret: "Client Secret"

ProjectKey: "Project Key"

Localizationfolder: "Localization Folder"

LanguagesToBeTranslated:
  - en
  - hi


// TODO: Choose one  =>  devnagri / local
GlobalPreferenceInCaseOfMergeConflict: "Remote"
